"""
Extract the mirrored pedestrian sheet so the phone-snatcher reaches
from the OPPOSITE side too.

Source: /run/concept/npcs-pedestrians-flipped.png
        4 cols x 3 rows = 12 frames, white background.
        Row 1 (1-4):  hoodie dude walking
        Row 2 (5-8):  woman in red shirt + skirt walking
        Row 3 (9-12): hoodie reaching to the LEFT (phone-thief mirror)

Output: /run/img/sprites/npc-pedestrian-flipped-01..12.png

Same flood-fill-from-corners pipeline as the cop-officer + budgie +
mattress extractions. White is the bg color across the whole sheet.
"""

from collections import deque
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "run" / "concept" / "npcs-pedestrians-flipped.png"
DST_DIR = ROOT / "run" / "img" / "sprites"

COLS = 4
ROWS = 3
PREFIX = "npc-pedestrian-flipped-"


def flood_remove_corner_color(im, target=(255, 255, 255), tolerance=18):
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    tr, tg, tb = target
    visited = [[False] * h for _ in range(w)]

    def matches(x, y):
        r, g, b, a = px[x, y]
        if a == 0:
            return False
        return (abs(r - tr) <= tolerance
                and abs(g - tg) <= tolerance
                and abs(b - tb) <= tolerance)

    starts = [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]
    queue = deque()
    for sx, sy in starts:
        if not visited[sx][sy] and matches(sx, sy):
            queue.append((sx, sy))
            visited[sx][sy] = True
    while queue:
        x, y = queue.popleft()
        r, g, b, _ = px[x, y]
        px[x, y] = (r, g, b, 0)
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not visited[nx][ny] and matches(nx, ny):
                visited[nx][ny] = True
                queue.append((nx, ny))
    return im


def keep_largest_blob(im, alpha_threshold=30):
    w, h = im.size
    px = im.load()
    visited = [[False] * h for _ in range(w)]
    filled = [[False] * h for _ in range(w)]
    for x in range(w):
        for y in range(h):
            if px[x, y][3] >= alpha_threshold:
                filled[x][y] = True
    components = []
    for sx in range(w):
        for sy in range(h):
            if not filled[sx][sy] or visited[sx][sy]:
                continue
            comp = []
            q = deque([(sx, sy)])
            visited[sx][sy] = True
            while q:
                x, y = q.popleft()
                comp.append((x, y))
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and filled[nx][ny] and not visited[nx][ny]:
                        visited[nx][ny] = True
                        q.append((nx, ny))
            components.append(comp)
    if not components:
        return im
    largest = max(components, key=len)
    keep = set(largest)
    for x in range(w):
        for y in range(h):
            if filled[x][y] and (x, y) not in keep:
                r, g, b, _ = px[x, y]
                px[x, y] = (r, g, b, 0)
    return im


def trim_transparent(im):
    bbox = im.getbbox()
    return im.crop(bbox) if bbox else im


def detect_corner_bg(im):
    """Sample the 4 corners of a cell + return the most common color.
    Each cell in this sheet has its OWN bg (alternating grey/white
    checkerboard pattern), so per-cell detection beats a global pass."""
    from collections import Counter
    px = im.load()
    w, h = im.size
    corners = [px[0, 0][:3], px[w-1, 0][:3], px[0, h-1][:3], px[w-1, h-1][:3]]
    return Counter(corners).most_common(1)[0][0]


def main():
    if not SRC.exists():
        print(f"SRC missing: {SRC}")
        return
    sheet = Image.open(SRC).convert("RGBA")
    w, h = sheet.size
    cw = w // COLS
    ch = h // ROWS
    DST_DIR.mkdir(parents=True, exist_ok=True)
    idx = 1
    for row in range(ROWS):
        for col in range(COLS):
            box = (col * cw, row * ch, (col + 1) * cw, (row + 1) * ch)
            cell = sheet.crop(box).copy()
            # Each cell has its own bg color (grey or white in this
            # sheet's checkerboard pattern). Auto-detect from corners.
            bg = detect_corner_bg(cell)
            cell = flood_remove_corner_color(cell, target=bg, tolerance=22)
            cell = keep_largest_blob(cell)
            cell = trim_transparent(cell)
            # MIRROR: source sheet was generated by Gemini but the
            # poses came out roughly the same direction as the original
            # sheet (hoodies still facing the same way). Flip
            # horizontally to guarantee a true mirror — the
            # phone-snatcher in row 3 then reaches from the opposite
            # side, which is the actual gameplay reason for this
            # second sheet existing.
            cell = cell.transpose(Image.FLIP_LEFT_RIGHT)
            name = f"{PREFIX}{idx:02d}.png"
            cell.save(DST_DIR / name, "PNG", optimize=True)
            print(f"wrote {name}  bg={bg}  ({cell.size[0]}x{cell.size[1]})")
            idx += 1
    print("done.")


if __name__ == "__main__":
    main()
